---
- name: Install Docker based on OS family
  hosts: servers
  become: yes
  tasks:
  
    - name: Install Docker  on Debian-based systems 
      apt:
        name: docker.io
        state: latest
      when: ansible_os_family == "Debian"
    
    - name: Install Docker on RedHat-based systems 
      yum:
        name: docker.io
        state: latest
      when: ansible_os_family == "RedHat"

