---
- name: Install and Start a Service
  hosts: servers
  become: yes
  vars:
  
    package_name: "nginx"
    service_name: "nginx"

  tasks:
    - name: Install the package
      apt:
        name: "{{ package_name }}"
        state: present
        update_cache: yes

    - name: Ensure the service is started and enabled
      service:
        name: "{{ service_name }}"
        state: started
        enabled: yes
