---
- name: Manage directories and files with loop
  hosts: servers
  become: yes
  tasks:
    - name: Ensure the directories exist with correct permissions
      file:
        path: "{{ item.path }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - { path: "/home/ubuntu/app1" }
        - { path: "/home/ubuntu/app2" }

    - name: Ensure specific files exist with correct permissions
      file:
        path: "{{ item.path }}"
        state: touch
        mode: '0644'
        owner: root
        group: root
      loop:
        - { path: "/home/ubuntu/app1/config.conf" }
        - { path: "/home/ubuntu/app2/config.conf" }
        