---
- name: Install Nginx and host index.html
  hosts: servers
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create the directory for the HTML file
      file:
        path: /var/www/html
        state: directory
        mode: '0755'

    - name: Copy index.html to the server
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Copy Nginx configuration file
      copy:
        src: files/nginx-default
        dest: /etc/nginx/sites-available/default
        mode: '0644'
      notify:
        - Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

# -
#   name: nginx
#   hosts: servers
#   become: yes
#   tasks:
#     - name: Install Nginx
#       ansible.builtin.package:
#         name: nginx
#         state: present

#     - name: Ensure Nginx is running
#       ansible.builtin.service:
#         name: nginx
#         state: started
#         enabled: yes

#     - name: Deploy index.html
#       ansible.builtin.copy:
#         src: index.html
#         dest: /var/www/html/index.html

#conf file


# server {
#     listen 80;
#     server_name localhost;
#     root /var/www/html;
#     index index.html;
#     location / {
#         try_files $uri $uri/ =404;
#     }
# }
